// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/prover.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProofRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ProofData:
	//
	//	*ProofRequest_Membership
	//	*ProofRequest_Range
	ProofData     isProofRequest_ProofData `protobuf_oneof:"proof_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProofRequest) Reset() {
	*x = ProofRequest{}
	mi := &file_proto_prover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofRequest) ProtoMessage() {}

func (x *ProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofRequest.ProtoReflect.Descriptor instead.
func (*ProofRequest) Descriptor() ([]byte, []int) {
	return file_proto_prover_proto_rawDescGZIP(), []int{0}
}

func (x *ProofRequest) GetProofData() isProofRequest_ProofData {
	if x != nil {
		return x.ProofData
	}
	return nil
}

func (x *ProofRequest) GetMembership() *MembershipRequest {
	if x != nil {
		if x, ok := x.ProofData.(*ProofRequest_Membership); ok {
			return x.Membership
		}
	}
	return nil
}

func (x *ProofRequest) GetRange() *RangeRequest {
	if x != nil {
		if x, ok := x.ProofData.(*ProofRequest_Range); ok {
			return x.Range
		}
	}
	return nil
}

type isProofRequest_ProofData interface {
	isProofRequest_ProofData()
}

type ProofRequest_Membership struct {
	Membership *MembershipRequest `protobuf:"bytes,1,opt,name=membership,proto3,oneof"`
}

type ProofRequest_Range struct {
	Range *RangeRequest `protobuf:"bytes,2,opt,name=range,proto3,oneof"`
}

func (*ProofRequest_Membership) isProofRequest_ProofData() {}

func (*ProofRequest_Range) isProofRequest_ProofData() {}

type MembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActualValue   string                 `protobuf:"bytes,1,opt,name=actual_value,json=actualValue,proto3" json:"actual_value,omitempty"`
	ActualSalt    string                 `protobuf:"bytes,2,opt,name=actual_salt,json=actualSalt,proto3" json:"actual_salt,omitempty"` // Hex string
	Siblings      []string               `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty"`                       // Hex strings
	PublicList    []string               `protobuf:"bytes,4,rep,name=public_list,json=publicList,proto3" json:"public_list,omitempty"`
	PublicRoot    string                 `protobuf:"bytes,5,opt,name=public_root,json=publicRoot,proto3" json:"public_root,omitempty"` // Hex string
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipRequest) Reset() {
	*x = MembershipRequest{}
	mi := &file_proto_prover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipRequest) ProtoMessage() {}

func (x *MembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipRequest.ProtoReflect.Descriptor instead.
func (*MembershipRequest) Descriptor() ([]byte, []int) {
	return file_proto_prover_proto_rawDescGZIP(), []int{1}
}

func (x *MembershipRequest) GetActualValue() string {
	if x != nil {
		return x.ActualValue
	}
	return ""
}

func (x *MembershipRequest) GetActualSalt() string {
	if x != nil {
		return x.ActualSalt
	}
	return ""
}

func (x *MembershipRequest) GetSiblings() []string {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *MembershipRequest) GetPublicList() []string {
	if x != nil {
		return x.PublicList
	}
	return nil
}

func (x *MembershipRequest) GetPublicRoot() string {
	if x != nil {
		return x.PublicRoot
	}
	return ""
}

func (x *MembershipRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActualValue   uint32                 `protobuf:"varint,1,opt,name=actual_value,json=actualValue,proto3" json:"actual_value,omitempty"`
	ActualSalt    string                 `protobuf:"bytes,2,opt,name=actual_salt,json=actualSalt,proto3" json:"actual_salt,omitempty"` // Hex string
	Siblings      []string               `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty"`                       // Hex strings
	LowerBound    uint32                 `protobuf:"varint,4,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	UpperBound    uint32                 `protobuf:"varint,5,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	PublicRoot    string                 `protobuf:"bytes,6,opt,name=public_root,json=publicRoot,proto3" json:"public_root,omitempty"` // Hex string
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_proto_prover_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prover_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_prover_proto_rawDescGZIP(), []int{2}
}

func (x *RangeRequest) GetActualValue() uint32 {
	if x != nil {
		return x.ActualValue
	}
	return 0
}

func (x *RangeRequest) GetActualSalt() string {
	if x != nil {
		return x.ActualSalt
	}
	return ""
}

func (x *RangeRequest) GetSiblings() []string {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *RangeRequest) GetLowerBound() uint32 {
	if x != nil {
		return x.LowerBound
	}
	return 0
}

func (x *RangeRequest) GetUpperBound() uint32 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

func (x *RangeRequest) GetPublicRoot() string {
	if x != nil {
		return x.PublicRoot
	}
	return ""
}

func (x *RangeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId     string                 `protobuf:"bytes,1,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	Cycles        uint32                 `protobuf:"varint,2,opt,name=cycles,proto3" json:"cycles,omitempty"`
	ReceiptBytes  []byte                 `protobuf:"bytes,3,opt,name=receipt_bytes,json=receiptBytes,proto3" json:"receipt_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProofResponse) Reset() {
	*x = ProofResponse{}
	mi := &file_proto_prover_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofResponse) ProtoMessage() {}

func (x *ProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prover_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofResponse.ProtoReflect.Descriptor instead.
func (*ProofResponse) Descriptor() ([]byte, []int) {
	return file_proto_prover_proto_rawDescGZIP(), []int{3}
}

func (x *ProofResponse) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *ProofResponse) GetCycles() uint32 {
	if x != nil {
		return x.Cycles
	}
	return 0
}

func (x *ProofResponse) GetReceiptBytes() []byte {
	if x != nil {
		return x.ReceiptBytes
	}
	return nil
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId     string                 `protobuf:"bytes,1,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	ProofType     string                 `protobuf:"bytes,2,opt,name=proof_type,json=proofType,proto3" json:"proof_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_proto_prover_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prover_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_prover_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyRequest) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *VerifyRequest) GetProofType() string {
	if x != nil {
		return x.ProofType
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_proto_prover_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prover_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_prover_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_proto_prover_proto protoreflect.FileDescriptor

const file_proto_prover_proto_rawDesc = "" +
	"\n" +
	"\x12proto/prover.proto\x12\x06prover\"\x87\x01\n" +
	"\fProofRequest\x12;\n" +
	"\n" +
	"membership\x18\x01 \x01(\v2\x19.prover.MembershipRequestH\x00R\n" +
	"membership\x12,\n" +
	"\x05range\x18\x02 \x01(\v2\x14.prover.RangeRequestH\x00R\x05rangeB\f\n" +
	"\n" +
	"proof_data\"\xc9\x01\n" +
	"\x11MembershipRequest\x12!\n" +
	"\factual_value\x18\x01 \x01(\tR\vactualValue\x12\x1f\n" +
	"\vactual_salt\x18\x02 \x01(\tR\n" +
	"actualSalt\x12\x1a\n" +
	"\bsiblings\x18\x03 \x03(\tR\bsiblings\x12\x1f\n" +
	"\vpublic_list\x18\x04 \x03(\tR\n" +
	"publicList\x12\x1f\n" +
	"\vpublic_root\x18\x05 \x01(\tR\n" +
	"publicRoot\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\"\xe5\x01\n" +
	"\fRangeRequest\x12!\n" +
	"\factual_value\x18\x01 \x01(\rR\vactualValue\x12\x1f\n" +
	"\vactual_salt\x18\x02 \x01(\tR\n" +
	"actualSalt\x12\x1a\n" +
	"\bsiblings\x18\x03 \x03(\tR\bsiblings\x12\x1f\n" +
	"\vlower_bound\x18\x04 \x01(\rR\n" +
	"lowerBound\x12\x1f\n" +
	"\vupper_bound\x18\x05 \x01(\rR\n" +
	"upperBound\x12\x1f\n" +
	"\vpublic_root\x18\x06 \x01(\tR\n" +
	"publicRoot\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\"k\n" +
	"\rProofResponse\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x01 \x01(\tR\treceiptId\x12\x16\n" +
	"\x06cycles\x18\x02 \x01(\rR\x06cycles\x12#\n" +
	"\rreceipt_bytes\x18\x03 \x01(\fR\freceiptBytes\"M\n" +
	"\rVerifyRequest\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x01 \x01(\tR\treceiptId\x12\x1d\n" +
	"\n" +
	"proof_type\x18\x02 \x01(\tR\tproofType\"C\n" +
	"\x0eVerifyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg2\x8b\x01\n" +
	"\rProverService\x12<\n" +
	"\rGenerateProof\x12\x14.prover.ProofRequest\x1a\x15.prover.ProofResponse\x12<\n" +
	"\vVerifyProof\x12\x15.prover.VerifyRequest\x1a\x16.prover.VerifyResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_prover_proto_rawDescOnce sync.Once
	file_proto_prover_proto_rawDescData []byte
)

func file_proto_prover_proto_rawDescGZIP() []byte {
	file_proto_prover_proto_rawDescOnce.Do(func() {
		file_proto_prover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_prover_proto_rawDesc), len(file_proto_prover_proto_rawDesc)))
	})
	return file_proto_prover_proto_rawDescData
}

var file_proto_prover_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_prover_proto_goTypes = []any{
	(*ProofRequest)(nil),      // 0: prover.ProofRequest
	(*MembershipRequest)(nil), // 1: prover.MembershipRequest
	(*RangeRequest)(nil),      // 2: prover.RangeRequest
	(*ProofResponse)(nil),     // 3: prover.ProofResponse
	(*VerifyRequest)(nil),     // 4: prover.VerifyRequest
	(*VerifyResponse)(nil),    // 5: prover.VerifyResponse
}
var file_proto_prover_proto_depIdxs = []int32{
	1, // 0: prover.ProofRequest.membership:type_name -> prover.MembershipRequest
	2, // 1: prover.ProofRequest.range:type_name -> prover.RangeRequest
	0, // 2: prover.ProverService.GenerateProof:input_type -> prover.ProofRequest
	4, // 3: prover.ProverService.VerifyProof:input_type -> prover.VerifyRequest
	3, // 4: prover.ProverService.GenerateProof:output_type -> prover.ProofResponse
	5, // 5: prover.ProverService.VerifyProof:output_type -> prover.VerifyResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_prover_proto_init() }
func file_proto_prover_proto_init() {
	if File_proto_prover_proto != nil {
		return
	}
	file_proto_prover_proto_msgTypes[0].OneofWrappers = []any{
		(*ProofRequest_Membership)(nil),
		(*ProofRequest_Range)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_prover_proto_rawDesc), len(file_proto_prover_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_prover_proto_goTypes,
		DependencyIndexes: file_proto_prover_proto_depIdxs,
		MessageInfos:      file_proto_prover_proto_msgTypes,
	}.Build()
	File_proto_prover_proto = out.File
	file_proto_prover_proto_goTypes = nil
	file_proto_prover_proto_depIdxs = nil
}
