// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDigitalCopy(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateDigitalCopy'](arg1, arg2, arg3);
}

export function Download(arg1, arg2, arg3) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3);
}

export function Encrypt(arg1, arg2) {
  return window['go']['main']['App']['Encrypt'](arg1, arg2);
}

export function FetchAndParseCertificate(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchAndParseCertificate'](arg1, arg2, arg3);
}

export function GenerateZKPOffline(arg1, arg2) {
  return window['go']['main']['App']['GenerateZKPOffline'](arg1, arg2);
}

export function GenerateZKPOnline(arg1, arg2) {
  return window['go']['main']['App']['GenerateZKPOnline'](arg1, arg2);
}

export function GetAcceptedDocs() {
  return window['go']['main']['App']['GetAcceptedDocs']();
}

export function GetAllDocs() {
  return window['go']['main']['App']['GetAllDocs']();
}

export function GetFileAndPath() {
  return window['go']['main']['App']['GetFileAndPath']();
}

export function GetPendingDocuments() {
  return window['go']['main']['App']['GetPendingDocuments']();
}

export function GetRejectedDocuments() {
  return window['go']['main']['App']['GetRejectedDocuments']();
}

export function IsApprovedInstitute() {
  return window['go']['main']['App']['IsApprovedInstitute']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function IssueCertificate(arg1) {
  return window['go']['main']['App']['IssueCertificate'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PrepareDigitalCopy(arg1) {
  return window['go']['main']['App']['PrepareDigitalCopy'](arg1);
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4);
}

export function TryDecrypt(arg1, arg2, arg3) {
  return window['go']['main']['App']['TryDecrypt'](arg1, arg2, arg3);
}

export function UploadDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadDocument'](arg1, arg2, arg3);
}

export function ViewDigitalCertificate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ViewDigitalCertificate'](arg1, arg2, arg3);
}

export function ViewDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['ViewDocument'](arg1, arg2, arg3);
}
