// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {blockchain} from '../models';

export function CreateDigitalCopy(arg1:number,arg2:string,arg3:models.CertificateBase_string_):Promise<string>;

export function Download(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Encrypt(arg1:Array<number>,arg2:string):Promise<Array<number>>;

export function FetchAndParseCertificate(arg1:string,arg2:string,arg3:string):Promise<models.CertificateBase_github_com_Suy56_ProofChain_internal_models_LeafFields_>;

export function GenerateZKPOffline(arg1:string,arg2:Array<string>):Promise<string>;

export function GenerateZKPOnline(arg1:string,arg2:Array<string>):Promise<string>;

export function GetAcceptedDocs():Promise<Array<blockchain.VerificationDocument>>;

export function GetAllDocs():Promise<Array<blockchain.VerificationDocument>>;

export function GetFileAndPath():Promise<Array<number>>;

export function GetPendingDocuments():Promise<Array<blockchain.VerificationDocument>>;

export function GetRejectedDocuments():Promise<Array<blockchain.VerificationDocument>>;

export function IsApprovedInstitute():Promise<boolean>;

export function IsLoggedIn():Promise<boolean>;

export function IssueCertificate(arg1:models.CertificateBase_string_):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function PrepareDigitalCopy(arg1:models.CertificateBase_string_):Promise<models.Document>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function TryDecrypt(arg1:Array<number>,arg2:string,arg3:string):Promise<Array<number>>;

export function UploadDocument(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ViewDigitalCertificate(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ViewDocument(arg1:string,arg2:string,arg3:string):Promise<string>;
